---
- hosts: all
  become: yes

  tasks: 
    - name: Install Apache
      yum: 
        name:
          - httpd
          - httpd-devel
        state: present
    
    - name: Copy build from S3 to /var/www/html
      shell: aws s3 cp s3://myec2testbucket-123456/webpage/build/ . --recursive
      args:
        chdir: /var/www/html
    
    - name: Start Apache and configure to run at boot
      service:
        name: httpd
        state: started
        enabled: yes

